name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        project:
          - path: simple-blog
            name: simple-blog
          - path: strapi/wandaexchange-blog
            name: wandaexchange-blog
          - path: strapi/wandaexchange-blog-app
            name: wandaexchange-blog-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ matrix.project.path }}/package.json

      - name: Install dependencies (${{ matrix.project.name }})
        working-directory: ${{ matrix.project.path }}
        run: npm ci || npm install

      - name: Build (${{ matrix.project.name }})
        working-directory: ${{ matrix.project.path }}
        run: npm run build


